import type { Brand } from './types';

// Presentation-only translations. Original snapshots and score inputs stay unchanged.
const phrases: Record<string,string> = {
  'experimental design studio':'实验设计工作室','small manufacturer':'小型制造商','material lab':'材料实验室','traditional craft brand':'传统工艺品牌','ai technology company':'人工智能技术公司','packaging manufacturer':'包装制造商','furniture brand':'家具品牌','large consumer electronics brand':'消费电子品牌','retail space':'零售空间','museum':'博物馆','independent publisher':'独立出版机构','media brand':'媒体品牌','tea brand':'茶品牌','coffee brand':'咖啡品牌','fashion brand':'时尚品牌','spatial design studio':'空间设计工作室','cultural ip':'文化形象品牌','community brand':'社群品牌','food brand':'食品品牌','experimental event studio':'实验活动工作室','textile lab':'纺织实验室','digital experience studio':'数字体验工作室','logistics company':'物流公司','industrial manufacturer':'工业制造商','accounting service':'财税服务','outdoor community':'户外社群','sound studio':'声音工作室',
  'concept development':'概念开发','product design':'产品设计','visual direction':'视觉设计','prototyping':'原型制作','small-batch manufacturing':'小批量制造','material development':'材料研发','distribution':'渠道分销','production engineering':'生产工程','sustainable materials':'可持续材料','material research':'材料研究','traditional craft':'传统工艺','cultural storytelling':'文化叙事','ai technology':'人工智能技术','digital interaction':'数字交互','software development':'软件开发','packaging':'包装','furniture production':'家具生产','electronics':'电子技术','manufacturing':'生产制造','community building':'社群运营','event production':'活动制作','exhibition curation':'展览策划','content production':'内容制作','publishing':'出版','food development':'食品研发','tea sourcing':'茶叶采购','coffee roasting':'咖啡烘焙','textile development':'纺织研发','spatial design':'空间设计','food sourcing':'食材采购','logistics':'物流','warehousing':'仓储','tax reporting':'税务申报','audit preparation':'审计准备','payroll':'薪酬管理','compliance training':'合规培训','bookkeeping automation':'记账自动化','sound design':'声音设计','ceramics':'陶瓷',
  'environmentally conscious consumers':'环保消费者','creative professionals':'创意工作者','independent retailers':'独立零售商','digital creatives':'数字创作者','curious learners':'探索型学习者','local communities':'本地社群','home enthusiasts':'家居爱好者','fashion enthusiasts':'时尚爱好者','culture lovers':'文化爱好者','food lovers':'美食爱好者','industrial buyers':'工业采购方','freight operators':'货运运营者','procurement teams':'采购团队','finance departments':'财务部门','outdoor athletes':'户外运动者','nature lovers':'自然爱好者','designers':'设计师','collectors':'收藏者','makers':'创客','craftspeople':'手工艺人','technologists':'科技从业者','students':'学生','families':'家庭','readers':'读者','accountants':'会计人员','hikers':'徒步者','musicians':'音乐人',
  'experimental':'实验性','playful':'趣味','curious':'好奇','independent':'独立','practical':'务实','precise':'精确','sustainable':'可持续','traditional':'传统','careful':'细致','tactile':'重视触感','futuristic':'未来感','warm':'温暖','open':'开放','thoughtful':'深思熟虑','conventional':'稳健','formal':'严谨','risk-averse':'谨慎','adventurous':'探索',
  'Design':'设计','Manufacturing':'制造','Materials':'材料','Craft':'工艺','Technology':'技术','Packaging':'包装','Distribution':'渠道','Spaces':'空间','Culture':'文化','Content':'内容','Community':'社群','Events':'活动','Food & drink':'饮食','Textiles':'纺织','Interaction':'交互','Finance':'财税','Sound':'声音','Prototyping':'原型',
  'Weak Fit':'联系较弱','Peer / Same Tribe':'相近领域','Productive Tension':'互补差异','Mutual Complement':'双向互补','Production Partner':'生产伙伴','Distribution Bridge':'渠道连接','Technology Transfer':'技术协作','Capability Complement':'能力互补','Cultural Exchange':'文化交流','Audience Bridge':'受众连接','Creative Chemistry':'创意共鸣',
};
const lowerPhrases = Object.fromEntries(Object.entries(phrases).map(([a,b])=>[a.toLowerCase(),b]));
const pattern = new RegExp(Object.keys(lowerPhrases).sort((a,b)=>b.length-a.length).map(value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'gi');
export function chineseLabel(text:string) { return phrases[text] ?? lowerPhrases[text.toLowerCase()] ?? text; }
const intents:Record<string,string> = {
  'lantern-loom':'为日常空间制作可拆装的限量灯具。','seed-basin':'开展城市种植课程与社区快闪体验。','grain-orbit':'通过谷物饮食与食谱分享连接家庭。','tide-parcel':'以可回收包装开发日常护理系列。','frame-walk':'创作有关城市记忆的影像、图录与展览。','paper-comet':'制作支持日常创作的趣味文具。','pedal-pulse':'开发骑行产品并组织社区快闪骑行。','paw-patch':'为日常散步设计耐用的宠物用品。','dune-glass':'用回收玻璃制作限量手工器物。','scent-archive':'以气味产品和展览记录地方记忆。','sun-grid':'制作服务户外体验的便携能源产品。','play-fold':'以开放式玩具开展亲子文化项目。',
  'memory-block':'制作实验性实体产品和限量器物系列。','form-works':'共同制作实验性实体产品和限量器物系列。','matter-matter':'把材料研究转化为实验性实体产品。','still-studio':'制作实验性实体产品和限量器物系列。','clay-county':'以数字体验和文化展览重新诠释工艺。','latent-lab':'以数字体验和文化展览连接工艺与人工智能。','fold-supply':'制作采用可重复使用包装的实验产品。','common-objects':'为日常空间打造限量实体产品。','circuit-house':'探索实验产品原型和趣味数字体验。','open-room':'开展快闪零售体验和文化展览。','field-museum':'为新受众创造文化展览和数字体验。','afterhours-press':'与新兴创作者共创编辑内容和文化项目。','signal-paper':'围绕创意工作制作内容和传播活动。','moss-tea':'创造饮茶仪式和快闪零售体验。','daybreak-coffee':'开展咖啡体验与快闪聚会。','soft-measure':'以限量穿戴系列探索实验性实体产品。','strata-studio':'打造文化展览和快闪零售空间。','little-myth':'围绕民间故事打造趣味数字体验和文化展览。','neighbourhood':'组织快闪聚会和文化项目。','hearth-foods':'通过时令品鉴菜单创造饮食体验。','tiny-assembly':'制作数字体验和文化展览。','loop-fibre':'用循环纺织材料开发实验产品。','point-practice':'创作数字体验和编辑内容。','line-of-work':'优化工业采购和企业货运流程。','bulk-union':'优化大批量通用零件的工业采购。','clear-ledger':'改善税务合规与法定财务报告。','wild-north':'组织户外探索和荒野远足。','quiet-type':'通过声音创造文化展览和实验数字体验。',
};
const names:Record<string,string> = {
  'memory-block':'记忆积木','form-works':'成形工坊','matter-matter':'材料之间','still-studio':'静物工作室','clay-county':'泥土郡','latent-lab':'潜像实验室','fold-supply':'折叠供应','common-objects':'日常器物','circuit-house':'电路之家','open-room':'开放空间','field-museum':'田野博物馆','afterhours-press':'夜航出版社','signal-paper':'信号纸刊','moss-tea':'苔茶','daybreak-coffee':'晨光咖啡','soft-measure':'柔软尺度','strata-studio':'层理空间','little-myth':'小小神话','neighbourhood':'邻里计划','hearth-foods':'炉边食集','tiny-assembly':'微型集会','loop-fibre':'循环纤维','point-practice':'点线交互','line-of-work':'工作线物流','bulk-union':'批量联合','clear-ledger':'清晰账本','wild-north':'野境北方','quiet-type':'静默字声','lantern-loom':'灯织工坊','seed-basin':'种子盆地','grain-orbit':'谷物轨道','tide-parcel':'潮汐包裹','frame-walk':'影格漫步','paper-comet':'纸上彗星','pedal-pulse':'骑行脉动','paw-patch':'爪印日常','dune-glass':'沙丘玻璃','scent-archive':'气味档案','sun-grid':'阳光电网','play-fold':'折叠玩乐',
};
export function displayBrand(brand:Brand):Brand {
  if(!intents[brand.id]) return brand;
  const translate=(text:string)=>text.replace(pattern,word=>lowerPhrases[word.toLowerCase()]).replace(/ and /g,'与').replace(/, /g,'、').replace(/\.$/,'。');
  const category=translate(brand.category);
  return {...brand,name:names[brand.id] ?? brand.name,visualSeed:brand.visualSeed ?? brand.name,category,summary:brand.fictional ? brand.summary : `${brand.name} 是一家${category}，正在探索新的合作方式。`,offers:translate(brand.offers),needs:translate(brand.needs),intent:intents[brand.id],audience:translate(brand.audience),identity:translate(brand.identity),constraints:brand.id==='bulk-union'?'仅接受十万件以上工业订单，不接受原型或限量项目。':'接受试点与跨领域合作，没有规模或地域限制。'};
}
