import { StrictMode, Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './components/brand-vi.css';
import './components/flow-design-system.css';
import './components/brand-ip.css';
import './collaboration/unified-ui.css';
const AvatarLab = lazy(() => import('./components/AvatarLab'));
const showLab = new URLSearchParams(window.location.search).get('view') === 'lab';
const AvatarStandards = lazy(() => import('./components/AvatarStandards'));
const showAvatars = new URLSearchParams(window.location.search).get('view') === 'avatars';
const CaseStudio = lazy(() => import('./cases/CaseStudio'));
const showCases = new URLSearchParams(window.location.search).get('view') === 'legacy-cases';
if (showCases) document.title = 'Memory Block · 合作参考案例';
createRoot(document.getElementById('root')!).render(<StrictMode>{showLab ? <Suspense fallback={<p>正在打开形象实验室…</p>}><AvatarLab /></Suspense> : showAvatars ? <Suspense fallback={<p>正在打开资料上传…</p>}><AvatarStandards /></Suspense> : showCases ? <Suspense fallback={<p style={{ padding: 32 }}>正在打开 Memory Block 的合作案例…</p>}><CaseStudio /></Suspense> : <App />}</StrictMode>);
