import { Icon } from '../components/Icon';
export function RelationsHome({ onExplore, onDraw, onCreate, onProjects }: { onExplore: () => void; onDraw: () => void; onCreate: () => void; onProjects: () => void }) {
  return <main className="br-home"><section className="br-hero"><svg className="br-response-arcs" viewBox="0 0 1440 700" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><path className="br-arc-black" d="M 1500 56 C 1090 -5 924 116 999 365" /><path className="br-arc-blue" d="M -180 695 C 332 678 757 635 866 393" /></svg><div className="br-hero-copy"><h1>让品牌之间，<br />有了下文。</h1><p>发现值得认识的品牌，<br />从一次对话，开始新的合作。</p><div><button className="br-button primary" onClick={onExplore}>寻找合作伙伴<Icon name="arrow" /></button><a href="#how-it-works" onClick={e => { e.preventDefault(); document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' }); }}>了解如何开始 ↗</a></div></div><p className="br-hero-signoff">不同的品牌，共同的可能。</p></section>
    <div className="br-journey"><span>认识彼此</span><i>/</i><span>看见交集</span><i>/</i><span>预演合作</span><i>/</i><span>开始对话</span></div>
    <section className="br-evidence-strip"><div><small>本期方案 · 库迪咖啡 × 奶龙</small><p>让治愈角色，<br className="br-mobile-break" />进入一杯咖啡的日常。</p></div><button onClick={onProjects}>看看联名预演<Icon name="arrow" /></button></section>
    <section className="br-how" id="how-it-works"><div className="br-how-heading"><h2>联系，从理解开始。</h2><p>保留各自的品牌本色，<br />让彼此在新的受众中被看见。</p></div><div className="br-routes"><article><span>01 / 有方向地寻找</span><p>围绕你的合作想法，<br />探索品牌之间的关系。</p><button className="br-text-button" onClick={onExplore}>进入 Gravity ↗</button><svg viewBox="0 0 400 65" aria-hidden="true"><path d="M0 14C90 4 130 54 190 45M210 45C280 52 316 0 400 10"/><circle cx="192" cy="45" r="5"/><circle cx="210" cy="45" r="5"/></svg></article><article><span>02 / 给意外一次机会</span><p>发现一个品牌，<br />也发现一次值得开始的对话。</p><button className="br-text-button" onClick={onDraw}>试试抽卡 ↗</button><svg viewBox="0 0 400 65" aria-hidden="true"><path d="M0 15C75 12 108 47 180 45M220 45C290 52 320 0 400 10M184 10l5 9M201 4v11M219 10l-5 9"/><circle cx="201" cy="44" r="8"/></svg></article><article><span>03 / 先让合作看得见</span><p>为同一个合作想法，<br />预演双方渠道里的呈现。</p><button className="br-text-button" onClick={onProjects}>打开联名项目 ↗</button><svg viewBox="0 0 400 65" aria-hidden="true"><rect x="144" y="9" width="42" height="50"/><rect x="214" y="9" width="42" height="50"/><path d="M194 34h12M200 28v12M0 34h126M274 34h126"/></svg></article></div></section>
    <section className="br-home-cta"><h2>好的合作，<br />先从认识开始。</h2><button className="br-button" onClick={onCreate}>介绍你的品牌<Icon name="arrow" /></button></section><footer className="br-home-footer"><span>Brand Relations</span><span>认识 · 相遇 · 共创</span><a href="?view=cases">合作案例参考 ↗</a></footer>
  </main>;
}
